### PR TITLE
add travis CI error report  when build fails

### PR DESCRIPTION
**Pull request by yunhanw-google**

### CODE REVIEW

**Comment by gerickson** [comment]
What is this adding that is not already present today?

**Comment by yunhanw-google** [comment]
> What is this adding that is not already present today?

It seems currently CI shows green if the test fails, 

https://travis-ci.org/openweave/openweave-core/jobs/543854076

============================================================================
# TOTAL: 177
# PASS:  175
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-apps/test-suite.log
Please report to weave.support@nestlabs.com
============================================================================
make[7]: *** [test-suite.log] Error 1
make[6]: *** [check-TESTS] Error 2
make[5]: *** [check-am] Error 2
make[4]: *** [check-recursive] Error 1
make[3]: *** [check-recursive] Error 1
make[2]: *** [check-recursive] Error 1
make[1]: *** [check] Error 2
make: *** [check-x86_64-unknown-linux-gnu] Error 2
cp: cannot stat ‘/tmp/happy*’: No such file or directory
please check happy-test-log/<UTC time> under link: https://storage.cloud.google.com/openweave
The command ".travis/script.sh" exited with 0.

**Comment by gerickson** [comment]
Thanks for clarifying. This seems like it is applying the fix in the incorrect, downstream location. Travis CI should reflect the exit status correctly when make fails. This should be consistent with manual invocation on a local machine in the shell. Is there some intervening process between the failure that is getting invoked that "eats" or masks the primary failure status?

I suspect:

```
cp: cannot stat ‘/tmp/happy*’: No such file or directory
please check happy-test-log/ under link: https://storage.cloud.google.com/openweave
```

is the source of that offending "eating" or "masking" and the problem should be fixed there such that the correct status is passed through.

**Comment by jenniexie** [comment]
Spoke to Yunhan for this one, I will take a look for this Travis CI issue

**Comment by yunhanw-google** [comment]
Just

> Spoke to Yunhan for this one, I will take a look for this Travis CI issue

please try this potential fix, thanks

**Comment by jenniexie** [comment]
> Just
> 
> > Spoke to Yunhan for this one, I will take a look for this Travis CI issue
> 
> please try this potential fix, thanks

sure, will do, Thanks

**Comment by gerickson** [comment]
As expected, the problem here is absolutely gcc_check_happy in .travis/script.sh:

```
gcc_check_happy()
{
    cmd_start="sudo make -f Makefile-Standalone DEBUG=1 TIMESTAMP=1 COVERAGE=1 "
    cmd_end="BuildJobs=24 check"

    if [ "lwip" in "${BUILD_TARGET}" ];then
        build_cmd="$cmd_start USE_LWIP=1 $cmd_end"
        build_folder="x86_64-unknown-linux-gnu-lwip"
    else
        build_cmd="$cmd_start $cmd_end"
        build_folder="x86_64-unknown-linux-gnu"
    fi

    mkdir -p $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
    eval $build_cmd
    cp $TRAVIS_BUILD_DIR/build/$build_folder/src/test-apps/happy $TRAVIS_BUILD_DIR/happy-test-logs/$1 -rf
    cp /tmp/happy* $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
    echo "please check happy-test-log/<UTC time> under link: https://storage.cloud.google.com/openweave"
}
```

The code `eval $build_cmd` will return the status of make in `${?}`. That needs to be saved and preserved immediately following `eval $build_cmd` and then returned before `gcc_check_happy` completes at `}`. Otherwise, each of the `cp` and `echo` lines will overwrite `${?}`. Since `echo ` will always succeed, gcc_check_happy will always succeed, and Travis CI will always believe such matrix targets have succeeded, even when they do not.

Something like the following is the better and preferred fix for this since the problem exists here and not in the openweave-core build system itself:

```
    ...
    eval $build_cmd
    make_status=${?}
    cp $TRAVIS_BUILD_DIR/build/$build_folder/src/test-apps/happy $TRAVIS_BUILD_DIR/happy-test-logs/$1 -rf
    cp /tmp/happy* $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
    echo "please check happy-test-log/<UTC time> under link: https://storage.cloud.google.com/openweave"

    return ${make_status}
}
```

**Comment by jenniexie** [comment]
> As expected, the problem here is absolutely gcc_check_happy in .travis/script.sh:
> 
> ```
> gcc_check_happy()
> {
>     cmd_start="sudo make -f Makefile-Standalone DEBUG=1 TIMESTAMP=1 COVERAGE=1 "
>     cmd_end="BuildJobs=24 check"
> 
>     if [ "lwip" in "${BUILD_TARGET}" ];then
>         build_cmd="$cmd_start USE_LWIP=1 $cmd_end"
>         build_folder="x86_64-unknown-linux-gnu-lwip"
>     else
>         build_cmd="$cmd_start $cmd_end"
>         build_folder="x86_64-unknown-linux-gnu"
>     fi
> 
>     mkdir -p $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
>     eval $build_cmd
>     cp $TRAVIS_BUILD_DIR/build/$build_folder/src/test-apps/happy $TRAVIS_BUILD_DIR/happy-test-logs/$1 -rf
>     cp /tmp/happy* $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
>     echo "please check happy-test-log/<UTC time> under link: https://storage.cloud.google.com/openweave"
> }
> ```
> 
> The code `eval $build_cmd` will return the status of make in `${?}`. That needs to be saved and preserved immediately following `eval $build_cmd` and then returned before `gcc_check_happy` completes at `}`. Otherwise, each of the `cp` and `echo` lines will overwrite `${?}`. Since `echo ` will always succeed, gcc_check_happy will always succeed, and Travis CI will always believe such matrix targets have succeeded, even when they do not.
> 
> Something like the following is the better and preferred fix for this since the problem exists here and not in the openweave-core build system itself:
> 
> ```
>     ...
>     eval $build_cmd
>     make_status=${?}
>     cp $TRAVIS_BUILD_DIR/build/$build_folder/src/test-apps/happy $TRAVIS_BUILD_DIR/happy-test-logs/$1 -rf
>     cp /tmp/happy* $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
>     echo "please check happy-test-log/<UTC time> under link: https://storage.cloud.google.com/openweave"
> 
>     return ${make_status}
> }
> ```

Thanks @gerickson this is very helpful! I will try it out.

**Comment by yunhanw-google** [comment]
> As expected, the problem here is absolutely gcc_check_happy in .travis/script.sh:
> 
> ```
> gcc_check_happy()
> {
>     cmd_start="sudo make -f Makefile-Standalone DEBUG=1 TIMESTAMP=1 COVERAGE=1 "
>     cmd_end="BuildJobs=24 check"
> 
>     if [ "lwip" in "${BUILD_TARGET}" ];then
>         build_cmd="$cmd_start USE_LWIP=1 $cmd_end"
>         build_folder="x86_64-unknown-linux-gnu-lwip"
>     else
>         build_cmd="$cmd_start $cmd_end"
>         build_folder="x86_64-unknown-linux-gnu"
>     fi
> 
>     mkdir -p $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
>     eval $build_cmd
>     cp $TRAVIS_BUILD_DIR/build/$build_folder/src/test-apps/happy $TRAVIS_BUILD_DIR/happy-test-logs/$1 -rf
>     cp /tmp/happy* $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
>     echo "please check happy-test-log/<UTC time> under link: https://storage.cloud.google.com/openweave"
> }
> ```
> 
> The code `eval $build_cmd` will return the status of make in `${?}`. That needs to be saved and preserved immediately following `eval $build_cmd` and then returned before `gcc_check_happy` completes at `}`. Otherwise, each of the `cp` and `echo` lines will overwrite `${?}`. Since `echo ` will always succeed, gcc_check_happy will always succeed, and Travis CI will always believe such matrix targets have succeeded, even when they do not.
> 
> Something like the following is the better and preferred fix for this since the problem exists here and not in the openweave-core build system itself:
> 
> ```
>     ...
>     eval $build_cmd
>     make_status=${?}
>     cp $TRAVIS_BUILD_DIR/build/$build_folder/src/test-apps/happy $TRAVIS_BUILD_DIR/happy-test-logs/$1 -rf
>     cp /tmp/happy* $TRAVIS_BUILD_DIR/happy-test-logs/$1/from-tmp
>     echo "please check happy-test-log/<UTC time> under link: https://storage.cloud.google.com/openweave"
> 
>     return ${make_status}
> }
> ```

thanks, grant, just update the pr and comments per your suggestion.

**Pull request merged**
