### PR TITLE
Add LwIP-based Network and Service Tests

### PR DESCRIPTION
**Pull request by gerickson**
This pull request adds LwIP-based network and service tests to the Travis continuous integration matrix.

### CODE REVIEW

**Comment by jenniexie** [comment]
because I don't have permission for pushing code directly to openweave-core repo, I am testing it out on my repo:
https://github.com/jenniexie/openweave-core
test result is here:
https://travis-ci.org/jenniexie/openweave-core/jobs/502783939
only test cases failed from travis CI test:
FAIL: happy/tests/standalone/time/test_weave_time_local.sh
FAIL: happy/tests/standalone/time/test_weave_time_auto.sh
I will debug it on my local and try to fix it.

**Comment by jenniexie** [comment]
the interesting thing is when I run manually on my local as single test, the tests are passing:
jexie@jexie0:~/github/openweave-core/src/test-apps/happy/tests/standalone/time$ ./test_weave_time_01.py --syncmode auto
weave-time test among server node03 (fd00:0000:fab1:0006:1ab4:3000:0000:000a), client node01 (fd00:0000:fab1:0006:1ab4:3000:0000:0004), coordinator node02 (fd00:0000:fab1:0006:1ab4:3000:0000:0005) with auto mode: 
Time sync succeeded
time sync test among client:node01, coordinator:node02, server:node03, sync mode:auto
Passed
2019-03-06 14:08:24,836 [HappyNodeAddress] [node01] HappyNodeAddress: virtual node node01 may not have any addresses on prefix fd00:0000:fab1:0000.
2019-03-06 14:08:26,380 [HappyNodeAddress] [node02] HappyNodeAddress: virtual node node02 may not have any addresses on prefix fd00:0000:fab1:0000.
2019-03-06 14:08:27,884 [HappyNodeAddress] [node03] HappyNodeAddress: virtual node node03 may not have any addresses on prefix fd00:0000:fab1:0000.
.
----------------------------------------------------------------------
Ran 1 test in 63.013s

OK
Deleting the plaid network
state.isStateEmpty(): True
The happy state is now empty, deleting the file
jexie@jexie0:~/github/openweave-core/src/test-apps/happy/tests/standalone/time$ ./test_weave_time_01.py --syncmode local
weave-time test among server node03 (fd00:0000:fab1:0006:1ab4:3000:0000:000a), client node01 (fd00:0000:fab1:0006:1ab4:3000:0000:0004), coordinator node02 (fd00:0000:fab1:0006:1ab4:3000:0000:0005) with local mode: 
Time sync succeeded
time sync test among client:node01, coordinator:node02, server:node03, sync mode:local
Passed
2019-03-06 14:09:58,080 [HappyNodeAddress] [node01] HappyNodeAddress: virtual node node01 may not have any addresses on prefix fd00:0000:fab1:0000.
2019-03-06 14:09:59,596 [HappyNodeAddress] [node02] HappyNodeAddress: virtual node node02 may not have any addresses on prefix fd00:0000:fab1:0000.
2019-03-06 14:10:01,136 [HappyNodeAddress] [node03] HappyNodeAddress: virtual node node03 may not have any addresses on prefix fd00:0000:fab1:0000.
.
----------------------------------------------------------------------
Ran 1 test in 61.039s

OK
Deleting the plaid network
state.isStateEmpty(): True
The happy state is now empty, deleting the file

**Comment by jenniexie** [comment]
I added gcs interface for test logs, here is the test log for 2 failure test cases:
https://pantheon.corp.google.com/storage/browser/openweave/happy-test-log/2019-03-07-04-46-19/tests/standalone/time/?project=openweave-test-project&authuser=0&organizationId=433637338589
It maybe resource conflict because running single test case is not failing, but running with all test cases are failing. I will try to dig in logs for more tomorrow.

**Comment by robszewczyk** [comment]
@gerickson -- with the PR#175 merged, this PR should succeed.  Would it be OK with you if I rebase this branch on top of master to get clean builds?

**Comment by gerickson** [comment]
> @gerickson -- with the PR#175 merged, this PR should succeed. Would it be OK with you if I rebase this branch on top of master to get clean builds?

Rebased and pushed.

**Comment by jenniexie** [comment]
@robszewczyk @gerickson  please go ahead with rebasing master for this PR, since I do not have permission to work directly on this branch.

**Comment by gerickson** [comment]
I’ve rebased and pushed.

**Pull request merged**
